### ISSUE TITLE
How to parallelize independent runs?

### ISSUE THREAD

**Issue by dsgranadosv** [HITS-MBM/conan#1]
Hi! I am using CONAN for making contact maps for multiple independent trajectories generated by clustering analysis. I have tried to build a bash script for analyzing all the systems at the same time using GNU Parallel with no luck. My problem relies in the folders that Conan writes for every run (frames, matrices, aggregate, etc) which are created in the folder of the bash script instead of being created in the the folder where the CONAN input file is located and executed

Do you know how to avoid this behaviour? Do you recommend any particular approach for running in parallel several conan inputs? 

Thanks in advance!

**Comment by csabadaday** [comment]
Hi Diego,


I would just rewrite the bash script such that CONAN is run from the proper working directory each time. This is what I do when I run it on several trajectories. In a way, it makes more sense this way, since usually I only have 1 input file and 10 trajectories, not vice versa.


So something like (assuming you choose Protein-H):

for i in {1..10}

do cd $i

echo 2 | conan.py ../conan.inp

cd ..;

done


Parallel runs will not really help, since the main bottleneck of conan is file I/O (in particular, reading in the big dmf.xpm file) and that is, as far as I understand, done in serial.


Another thing you can do is run gmx mdmat only as a first step, and then unite the dmf.xpm files (concatenate). If you want to make the time information unique, you can use the option "PATCH_TIME yes". Once you are happy with your conan input, just stop the session and copy the gmx command (every gmx command repeats the command on the screen).


This will make the run faster, assuming you want to average your quantities across independent runs, or want to cluster all frames, or ....


Let me know if these are good solutions to your problem.


Best,

    ?Csaba

Dr. Csaba Daday
Postdoc
Molecular Biomechanics

HITS gGmbH
Schloss-Wolfsbrunnenweg 35
69118 Heidelberg
Germany

phone   +49 6221 533 311
fax   +49 6221 533 298
email: csaba.daday@h-its.org
http://www.h-its.org<http://www.h-its.org/>
_________________________________________________
Amtsgericht Mannheim / HRB 337446
Managing Director: Dr. Gesa Schönberger
Scientific Director: Prof. Dr. Michael Strube

________________________________
